<?xml version="1.0"?>
<!--
Created on Thu Jan 18 2024

@author: hifzhil
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mevi"> 
    <xacro:include filename="$(find spawn_car)/model/mevi/urdf/vehicle_properties.urdf.xacro"/>
    <xacro:include filename="$(find spawn_car)/model/mevi/urdf/bases/mevi_body.gazebo.xacro"/>
    
    <material name="chassis_mat">
        <color rgba="0.2 0.2 0.2 1"/>
        <!-- grey -->
    </material>

    <xacro:macro name="mevi_base" params="name">
        <link name="dummy">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
            </visual>
        </link>
    
        <joint name="world_to_vehicle_center" type="fixed">
            <parent link="dummy"/>
            <child link="chassis"/>
            <origin xyz="0.0 0.0 ${ground_clearance + (chassis_thickness/2)}"/>
            <axis xyz = "0 0 1"/>
        </joint>
    
        <link name="chassis">
            
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
                </geometry>
                <material name="chassis_mat"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
                </geometry>
            </collision>

            <xacro:inertia_of_body/>
        </link>
    </xacro:macro>

</robot>