<?xml version="1.0"?>

<!--
Created on Thu Jan 18 12:02:12 2024

@author: hifzhil
-->

<robot name="urban_properties" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- my name is urban-->  

    <!-- CONSTANT -->
    <xacro:property name="pi_constant" value="3.14159265" />
    <xacro:property name = "degree_90" value="1.57079633"/>
    <xacro:property name = "degree_180" value="3.14159265"/>
    <xacro:property name = "degree_270" value="4.71239"/>
    <xacro:property name = "degree_360" value="6.28319"/>

    <xacro:property name="car_length" value="1.490" />
    <xacro:property name="car_width" value="0.830" />
    <xacro:property name="car_height" value="1.550" />
    <xacro:property name="front_overhang" value="0.220" />
    <xacro:property name="rear_overhang" value="0.280" />

    <!-- misalkan urban adalah balok -->
    <xacro:property name="vehicle_volume" value="${car_length*car_width*car_height}"/>
    
    <xacro:property name="ground_clearance" value="0.07" />
    <xacro:property name="wheel_base" value="0.98" />
    <!-- chassis -->
    <xacro:property name="chassis_width" value="0.830" />
    <xacro:property name="chassis_length" value="1.49" />
    <xacro:property name="chassis_thickness" value="0.03" />
    <xacro:property name="chassis_mass" value="200" />
       <!-- variable -->

    <!-- aluminium density is 2.7 g/cmÂ³ or 2700 kg/m3-->
    <xacro:property name="body_density" value="2700.0" />
    <!-- density of all tyre brands is nearly the same which is around 1.1 gr/cm3 or 1100 kg/m3 -->
    <xacro:property name="wheel_density" value="1100.0" />

    <!-- fixed transformation 
        this value on rad. 1.570795 is a phi/2
    -->
    <xacro:property name="wheel_cylindrical_transform" value="1.570795" />

    <xacro:property name="front_tyre_radius" value="0.172"/>
    <xacro:property name="front_tyre_width" value="0.125"/>
    <xacro:property name="front_tyre_mass" value="10.0"/>

    <xacro:property name="rear_tyre_radius" value="0.172"/>
    <xacro:property name="rear_tyre_width" value="0.125"/>
    <xacro:property name="rear_tyre_mass" value="10.0"/>

    <xacro:property name="front_track" value="0.830" />
    <xacro:property name="rear_track" value="0.750" />

    <!-- mass -->
    <!-- let assume the mass of box same as half aluminium at it size-->
    <xacro:property name="body_mass" value="${body_density*body_volume*(1/2)}"/>
    <xacro:property name="wheel_mass" value="${wheel_density*wheel_volume}"/>

    <!-- moment inertia of wheel -->
    <!-- let we assume the wheel is a full cylinder, so
        I_z is inertia with respect to the rotational axis (z)
        I is inertia with respect to the x and y axis
        I_z = 1/2*(mr2)
        I = 1/4*(mr2) + 1/12*(ml2)
    -->
    <xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_radius*wheel_radius}"/>
    <xacro:property name="I_wheel" value="${1/12*wheel_mass*(3*wheel_radius*wheel_radius + wheel_length*wheel_length)}"/>


  <!-- this is macro that we can call it anywhere on code
      it defines all inertia component on the wheel
  -->
    <xacro:macro name="inertia_of_wheel">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="${I_wheel}"
                ixy="0.0"
                ixz="0.0"
                iyy="${I_wheel}"
                iyz="0.0"
                izz="${Iz_wheel}"
            />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertia_of_body">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${chassis_mass}"/>
            <inertia 
                ixy="0.0"
                ixz="0.0"
                iyz="0.0"
                ixx = "${(1/12)*chassis_mass*(chassis_width*chassis_width + chassis_thickness*chassis_thickness)}"
                iyy = "${(1/12)*chassis_mass*(chassis_length*chassis_length + chassis_thickness*chassis_thickness)}"
                izz = "${(1/12)*chassis_mass*(chassis_length*chassis_length + chassis_width*chassis_width)}"
            />
        </inertial>
    </xacro:macro>
</robot>
